debug: True
#pcd_data: /Users/dodkins/PCD_data/
pcd_data: &DIR /mnt/data0/dodkins/PCD_data/  # store this path as DIR
working_dir: &WDIR !join [*DIR, 200106/]  # concat DIR with that suffix and store as WDIR
point_num: &PN 4096
trainfile: !join [*WDIR, trainfile.h5]
testfile: !join [*WDIR, testfile.h5]

data:
  medis_config: "medis_params.py"

train:
  gpu: 1
  point_num: *PN
  batch: 4
  epoch: 200
  wd: 0.
  output_dir: *WDIR
  data_dir: *WDIR
  ml_meta: !join [*WDIR, ml_meta.pkl]

