debug: True
#pcd_data: /Users/dodkins/PCD_data/
pcd_data: &DIR ${WORKING_DIR}/PCD_data/  # store this path as DIR
working_dir: &WDIR !join [*DIR, 200110/]  # concat DIR with that suffix and store as WDIR
point_num: &PN 4096
trainfile: !join [*WDIR, trainfile.h5]
testfile: !join [*WDIR, testfile.h5]
test_frac: 0.2
dimensions: 4
max_planets: 1

data:
  medis_config: "medis_params.py"
  angles: [0] #[0,90,180,270]
  lods: [2.5] #[2,4,6]
  contrasts: [-2]  # [-2, -6]

train:
  gpu: 1
  point_num: *PN
  batch: 4
  epoch: 200
  wd: 0.
  output_dir: *WDIR
  data_dir: *WDIR
  ml_meta: !join [*WDIR, ml_meta.pkl]

