# A file to change and get stored in your working dir for reference

debug: True
pcd_data: &DIR ${WORKING_DIR}/PCD_data/  # store this path as DIR
working_dir: &WDIR !join [*DIR, 210112Hipb5319/]  # concat DIR with that suffix and store as WDIR
overwrite_cache: False
pointnet_version: 2
num_point: &PN 200000  #  # 131072 262144
trainfiles: !join [*WDIR, 'trainfile_{id}.h5']
testfiles: !join [*WDIR, 'testfile_{id}.h5']
dimensions: 4
task: sem_seg
classes: 2  # star=0, planet=1
pre_adi: False
model: minkowski  # minkowski  # lightgbm  #
savepath: !join [*WDIR, 'test95.pth']
weight_ratio: 0.01
learning_rate: 0.0001

data:
  num_indata: 10  # Total # of input data. int or leave blank if providing list of angles/lods/contrasts below
  null_frac: 0.  # num of input data that are null (no planet photons)
  test_frac: 0.2
  aug_ratio:   # For every 1 medis input duplicate and rotate it {aug_ratio} times
  medis_config: "medis_params.py"
  angles: (0,360)  #(0,360)  # int: duplicated {num_planet} times, list: no further processing, tuple: limits for random selection
  lods: (1,5) #,2,3,5,3]
  contrasts: (-4,-2) #(-4,-2) #,-2,-2,-2,-2]
  star_spectra: 6000
  planet_spectra: 1000 #(500,2000) #,3000,3000,3000,3000] # length(num_indata) + 1
  time_diff: False
  quantize: True
  batch_coords: True
  rot_rate: 15  # deg/min
  fwhm: 10
  degrade_factor: 1

train:
  gpu: 1
  num_point: *PN
  batch_size: 3  # todo use
  max_epoch: 5
  wd: 0.
  log_dir: *WDIR
  data_dir: *WDIR
  snr_data: !join [*WDIR, snr_data.pkl]
  pt_outputs: !join [*WDIR, pt_outputs.pkl]
  images: !join [*WDIR, images.pkl]
  learning_rate: 0.0001  # 1e-5   todo use
  cache_freq: 10  # todo use
  roc_probabilities: False

mec:
  dark_data: /darkdata/dodkins/mec/20200731/Hip5319/dither_2/drizzled_h5s/ # /work/dodkins/MEC/20200729/  # /darkdata/dodkins/mec/20200729/HR8799/stare/  # /mnt/data0/dodkins/mec/20200731/Hip5319/dither_2/drizzled_h5s/
  h5s: # [1596290345.h5, 1596290351.h5, ...] or leave blank for all in folder
  dithered: True  # use the RA/Dec columnsF and align in time vs use x/y from beammap with no time adjustment
  offset: [30, -40]  #[17.5, -35]  # [17.5, -45]  # area to crop
  glados_inputfiles: !join [*WDIR, 'inputfile_{id}.h5']
  companion_coords: [78, 104, 6]  # x,y,r  can get these values by eye with debug == True on MecObs()

