debug: True
pcd_data: &DIR ${WORKING_DIR}/PCD_data/  # store this path as DIR
working_dir: &WDIR !join [*DIR, 201017b/]  # concat DIR with that suffix and store as WDIR
overwrite_cache: False
pointnet_version: 2
num_point: &PN 200000  #  # 131072 262144
trainfiles: !join [*WDIR, 'trainfile_{id}.h5']
testfiles: !join [*WDIR, 'testfile_{id}.h5']
dimensions: 4
task: sem_seg
classes: 2  # star=0, planet=1
model:  minkowski  # lightgbm  #
savepath: !join [*WDIR, 'test95.pth']

data:
  num_indata: 10  # Total # of input data. int or leave blank if providing list of angles/lods/contrasts below
  null_frac: 0.  # num of input data that are null (no planet photons)
  test_frac: 0.1
  aug_ratio: 9  # For every 1 medis input duplicate and rotate it {aug_ratio} times
  medis_config: "medis_params.py"
  angles: 45  #(0,360)  # int: duplicated {num_planet} times, list: no further processing, tuple: limits for random selection
#  lods: [1,3,5,1,3,5,1,3,5,1,3,5,1,3,5,1,3,5,3,5]  # int: duplicated {num_planet} times, list: no further processing, tuple: limits for random selection
#  contrasts: [-2,-2,-2,-3,-3,-3,-4,-4,-4,-4,-4,-4,-3,-3,-3,-2,-2,-2,-4,-5]  # int: duplicated {num_planet} times, list: no further processing, tuple: limits for random selection
#  lods: [1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5]
#  contrasts: [-2,-2,-2,-2,-2,-3,-3,-3,-3,-3,-4,-4,-4,-4,-4,-5,-5,-5,-5,-5]
  lods: [1,7,5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5]
  contrasts: [-2,-2,-2,-3,-3,-3,-3,-3,-4,-4,-4,-4,-4,-5,-5,-5,-5,-5]
  star_spectra: 6000
  planet_spectra: (1000,1000) # length(num_indata) + 1
#  num_augs: 4  # number of rotations to apply to each input
  time_diff: False
#  trans_polar: False
#  normalize: False
  quantize: True
  batch_coords: True
  rot_rate: 1  # deg/min

train:
  gpu: 1
  num_point: *PN
  batch_size: 3  # todo use
  max_epoch: 100
  wd: 0.
  log_dir: *WDIR
  data_dir: *WDIR
  outputs: !join [*WDIR, outputs.pkl]
  pt_outputs: !join [*WDIR, pt_outputs.pkl]
  learning_rate: 0.0001  # 1e-5   todo use
  cache_freq: 10  # todo use
  roc_probabilities: False
#  out_collapse: mean  # mean | argmax  todo confirm and delete these options under new pytorch system
#  momentum: 0.9
#  optimizer: adam
#  decay_step: 500 #300000
#  decay_rate: 0.5
#  num_train_batch: 5  # load batches of train data with this size on each cycle in train()
#  num_test_batch: 2  # load batches of train data with this size on each cycle in train()

mec:
  dark_data: /mnt/data0/dodkins/mec/20200731/Hip5319/dither_2/drizzled_h5s/
  h5s: # [1596290345.h5, 1596290351.h5, ...] or leave blank for all in folder
  dithered: True  # use the RA/Dec columns and align in time vs use x/y from beammap with no time adjustment
  offset: [100, -55]  # area to crop
  glados_inputfiles: !join [*WDIR, 'inputfile_{id}.h5']
  companion_coords: [60, 174, 5]  # x,y,r  can get these values by eye with debug == True on MecObs()
