debug: True
pcd_data: &DIR ${WORKING_DIR}/PCD_data/  # store this path as DIR
working_dir: &WDIR !join [*DIR, 200121d/]  # concat DIR with that suffix and store as WDIR
num_point: &PN 4096
trainfiles: !join [*WDIR, 'trainfile_{id}.h5']
testfiles: !join [*WDIR, 'testfile_{id}.h5']
test_frac: 0.2
dimensions: 4
task: sem_seg
classes: 2  # star=0, planet=1

data:
  num_planets: 10 # int or leave blank if providing list of angles/lods/contrasts below
  medis_config: "medis_params.py"
  angles: (0, 360)  # int: duplicated {num_planet} times, list: no further processing, tuple: limits for random selection
  lods: (2, 4.5) # int: duplicated {num_planet} times, list: no further processing, tuple: limits for random selection
  contrasts: -2  # int: duplicated {num_planet} times, list: no further processing, tuple: limits for random selection

train:
  gpu: 1
  num_point: *PN
  batch_size: 100
  max_epoch: 200
  wd: 0.
  log_dir: *WDIR
  data_dir: *WDIR
  ml_meta: !join [*WDIR, ml_meta_rand.pkl]
  learning_rate: 0.001
  momentum: 0.9
  optimizer: adam
  decay_step: 300000
  decay_rate: 0.5
